apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: us.gcr.io/ticketspacific-tesinty-27017/tickets
          env: 
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: jwtSecret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtSecret
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
